---
abstract: 'Example widget with Hello World.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
  Tickit::Test: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tickit-Widget-HelloWorld
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  English: 0
  perl: 5.6.0
resources:
  bugtracker: https://github.com/tupinek/Tickit-Widget-HelloWorld/issues
  homepage: https://github.com/tupinek/Tickit-Widget-HelloWorld
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Tickit-Widget-HelloWorld
version: '0.01'
